#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define POINTING_DEVICE_MOTION_PIN GP4
#define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW
//#define POINTING_DEVICE_ROTATION_180
